### ISSUE TITLE
Failed to Collect Certificates

### ISSUE THREAD

**Issue by LadyDarwe** [JumppanenTomi/NoteSnap#7]
Tell me if I'm missing something, but my s20 won't let me download the APK, due to:

> INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl1984762576.tmp/0.apk: Attempt to get length of null array

Cannot wait to try this though. I'm looking for something very specific, and I'll see if it's suitable for what my needs are as soon as I can figure out this certificate issue.

**Comment by JumppanenTomi** [comment]
Thank you for notifying us. I have released a [patch](https://github.com/JumppanenTomi/NoteSnap/releases/tag/latest) to address the reported issue. If you have any feedback in the future, we would greatly appreciate it, as it helps us enhance both ourselves and our project.
